server:
  port: 8124
  servlet:
    context-path: /msbc
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        commons-log:
          #data-source-log-enabled: true
          statement-log-enabled: true
          statement-executable-sql-log-enable: true
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      connection-error-retry-attempts: 5
      break-after-acquire-failure: true
      validation-query-timeout: 1
      validation-query: SELECT 1 FROM DUAL


      datasource:
        username: MSBC3DBA
        password: asd232238866
        driver-class-name: dm.jdbc.driver.DmDriver
        url: jdbc:dm://localhost:5236/MSBC3DBA?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8


#   redis:
#      host: 127.0.0.1
#      port: 6379

# JWT配置
#jwt:
#   # 密匙Key
#   secret: JWTSecret
#   # HeaderKey
#   tokenHeader: Authorization
#   # Token前缀
#   tokenPrefix: Bearer
#   # 过期时间，单位秒
#   expiration: 30000
#   # 刷新时间，单位天
#   refreshTime: 7
#   # 配置白名单（不需要认证）
#   antMatchers: /login/**,/register/**,/static/**,/swagger-ui.html,/doc.html,/swagger-resources/**, /webjars/**, /v2/**, /swagger-ui.html/**

# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: AUTO
  configuration:
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 加密秘钥
aes:
  secret: 6hj$xggb@ssg#1ca
  iv: Mrm2L0qxAqy8DcZS
